/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import AuthForm from "./AuthForm";
import Footer from "./Footer";

function AuthLayout() {
  return (
    <main className="flex gap-5 max-md:flex-col">
      <section className="flex flex-col w-full max-md:ml-0 max-md:w-full">
        <div className="flex flex-col items-center pt-4 bg-neutral-900 max-w-[390px] max-sm:ml-px max-sm:max-w-[390px]">
          <Header />
          <AuthForm />
          <Footer />
        </div>
      </section>
    </main>
  );
}

export default AuthLayout;
