/**
 * This code was generated by Builder.io.
 */
import React from "react";
import FormDivider from "./FormDivider";
import InputField from "./InputField";

function AuthForm() {
  return (
    <form>
      <FormDivider text="Авторизация" />
      <InputField
        icon="https://cdn.builder.io/api/v1/image/assets/TEMP/cd22e0c043bf7cd1df7bfcfb0345d3cdbcbd0fe1b2144200dbc6bcd13efd139b?apiKey=b7d3f4d190804c3eb0ba290af8be198e&"
        placeholder="Имя пользователя"
        type="text"
        id="username"
      />
      <InputField
        icon="https://cdn.builder.io/api/v1/image/assets/TEMP/0e549a90665ff5ef5e3864cf68d7e6263d9973c4e8558510c6601d81b17292ff?apiKey=b7d3f4d190804c3eb0ba290af8be198e&"
        placeholder="Пароль"
        type="password"
        id="password"
      />
      <button className="px-16 py-2 mt-9 w-full text-2xl text-black whitespace-nowrap bg-amber-300 rounded-md max-w-[341px]">
        Войти
      </button>
    </form>
  );
}

export default AuthForm;
