/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Footer() {
  return (
    <footer className="flex relative flex-col self-stretch mt-48 w-full aspect-[5.571]">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/b3f641597e8e9e6707dbd11af3a0592fed2208866faadd523da68c746b22f13d?apiKey=b7d3f4d190804c3eb0ba290af8be198e&"
        alt=""
        className="object-cover absolute inset-0 size-full"
      />
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/d0df46561721a89ff13ee80ab81c476e9f731626bb07c7a8637010c4b22f04a6?apiKey=b7d3f4d190804c3eb0ba290af8be198e&"
        alt=""
        className="object-contain z-10 -mt-3 -mb-1 aspect-[4.18] w-[360px]"
      />
    </footer>
  );
}

export default Footer;
