/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Header() {
  return (
    <>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/075bf7cd8504ebc247d3e34ab23781242961e2f83cecd310124f51bb97319399?apiKey=b7d3f4d190804c3eb0ba290af8be198e&"
        alt=""
        className="object-contain w-full aspect-[4.05] max-sm:w-full"
      />
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/1c1d7a171ea3d078623265df69a7db0420cb06cc7b88ec04d97226c67e3b1bcd?apiKey=b7d3f4d190804c3eb0ba290af8be198e&"
        alt=""
        className="object-contain w-full aspect-[7.63] max-sm:w-full"
      />
    </>
  );
}

export default Header;
