/**
 * This code was generated by Builder.io.
 */
import React from "react";

function InputField({ icon, placeholder, type, id }) {
  return (
    <div className="flex gap-2.5 p-3 mt-4 w-full text-lg font-light rounded-2xl border-2 border-gray-700 border-solid bg-neutral-900 max-w-[341px] text-zinc-600 text-opacity-60">
      <img
        loading="lazy"
        src={icon}
        alt=""
        className="object-contain shrink-0 self-start aspect-square w-[19px]"
      />
      <label htmlFor={id} className="sr-only">
        {placeholder}
      </label>
      <input
        type={type}
        id={id}
        placeholder={placeholder}
        className="flex-auto w-[286px] bg-transparent border-none outline-none"
      />
    </div>
  );
}

export default InputField;
